### ISSUE TITLE
网站出问题了，看群里

### ISSUE THREAD

**Issue by ACGheitu** [n0099/TiebaMonitor#12]
114514

**Comment by n0099** [comment]
Sorry for the delayed response.

As I've just tested on https://n0099.net/tbm, only static frontend pages and some backend api work properly.

This should start at a half month ago at 1cfb298faf676fb7a88c3a4b25f83d6c51735347, and the DB structure has changed a lot since that for migrating to the new crawler rewritten in C# from the legacy php based one that written in three years ago.

I'm going to work on the backend and frontend in the near future after the crawler can run stably without manually interfering. 
You can track the latest changes at https://github.com/n0099/TiebaMonitor/commits/v2/fe and https://github.com/n0099/TiebaMonitor/commits/v2/be

**Comment by ACGheitu** [comment]
发的什么玩意

**Comment by ACGheitu** [comment]
看群里

**Comment by ACGheitu** [comment]
865796317

**Comment by ACGheitu** [comment]
syzx.me

**Comment by ACGheitu** [comment]
速度上qqq

**Comment by n0099** [comment]
This repo is about the tbm project only, for other sites managed by us you could contact @kokoro-aya

**Comment by ACGheitu** [comment]
你知不知道syzx崩了几天了，你还在这跟我在这扯皮是吧

**Comment by n0099** [comment]
Possible related: https://n0099.net/v/d/3243

**Comment by n0099** [comment]
Please stop spamming issues on this repo as I've already guided who you could ask for this at https://github.com/n0099/TiebaMonitor/issues/12#issuecomment-1194675256

**Comment by n0099** [comment]
I've registered a zulip server for collecting related people(including you) to discuss and resolve these issues, plz check out ur gmail inbox and agree to my invite.

**Comment by ACGheitu** [comment]
文件： H:\四叶重工\n0099 - syzx\[PC]猫忍之心3.rar
大小： 2, 235, 160, 246 字节
修改时间：2022-09-17 15:28:32
MD5： 1C464A6A772188FD3A02BA8C8325CA29
SHA1： 88971D05CF24F6FBEBA1AF143B3A3485FD9631CF

文件： H:\四叶重工\n0099 - syzx\【PC】女装山脉.rar
大小： 912, 653, 663 字节
修改时间：2022-09-20 02:16:18
MD5： EF0838F9219A88B7E396746798D3EB3C
SHA1： 3DBE2B371192286696E25180F392C8ACB76E75E2



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "n0099/TiebaMonitor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [n0099/TiebaMonitor] 网站出问题了，看群里 (Issue #12)





 
I've registered a zulip server for collecting related people(including you) to discuss and resolve these issues, plz check out ur gmail inbox and agree to my invite.
